### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by jvwong**
- Bypass a record if it has no PMID
- Bypass a chunk of records if there is an error in fetching
- Log the retrieval iteration time and the total run time 
- Use the request wrapper (`safe_fetch`)

Refs #17

### CODE REVIEW

**Comment by jvwong** [comment]
Sample logging output (`MAX_EFETCH_RETMAX = 1000`):

```
Enter start date (YYYY/MM/DD): 2021/01/03
Enter end date (YYYY/MM/DD): 2021/01/04
INFO:root:Total records: 6318
INFO:root:URL 1: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?retmax=100000&query_key=1&db=pubmed&rettype=uilist&retmode=text&WebEnv=MCID_601d8f19eefb554a2e30db0f&retstart=0
INFO:root:Retrieved docs 0 through 999 of 6317 in 9.498197078704834s
INFO:root:Retrieved docs 1000 through 1999 of 6317 in 11.152498245239258s
INFO:root:Retrieved docs 2000 through 2999 of 6317 in 10.953627824783325s
INFO:root:Retrieved docs 3000 through 3999 of 6317 in 10.306595087051392s
INFO:root:Retrieved docs 4000 through 4999 of 6317 in 10.449842929840088s
INFO:root:Retrieved docs 5000 through 5999 of 6317 in 9.743391990661621s
INFO:root:Retrieved docs 6000 through 6317 of 6317 in 3.5491480827331543s
INFO:root:Done writing data from 2021/01/03 to 2021/01/04 onto file named: test.json
INFO:root:Total run time for 6318 docs: 78.78711676597595s
```

**Comment by Anwesh1** [comment]
This is great!! Do we want to show times required for every 10,000 entries? Or is this so we can see the chunks being omitted if there are invalid entries?

**Comment by jvwong** [comment]
> This is great!! Do we want to show times required for every 10,000 entries? Or is this so we can see the chunks being omitted if there are invalid entries?

Notice in the sample I changed the `MAX_EFETCH_RETMAX` to 1 000 from 10 000 so it will currently output every 10 000.

**Comment by Anwesh1** [comment]
Oh okay, that's better, so worst case we lose a batch of 1,000 instead of 10,000.

**Comment by jvwong** [comment]
Well its set to whatever you want. 

If you're OK with this I can merge so your PR #19 is up to date as I 've changed main.py

**Comment by Anwesh1** [comment]
sounds good

**Pull request merged**
